CREATE DATABASE NewCarPoolDb;
GO

USE NewCarPoolDb;
GO

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FullName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(256) NOT NULL UNIQUE,
    PhoneNumber NVARCHAR(30) NOT NULL,
    PasswordHash NVARCHAR(500) NOT NULL,
    ProfileImagePath NVARCHAR(500) NULL,
    Rating DECIMAL(3,2) NOT NULL DEFAULT 5,
    IsAdmin BIT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAtUtc DATETIME2 NULL
);

CREATE TABLE RefreshTokens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash NVARCHAR(128) NOT NULL UNIQUE,
    ExpiresAtUtc DATETIME2 NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    RevokedAtUtc DATETIME2 NULL,
    ReplacedByTokenHash NVARCHAR(128) NULL,
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE PasswordResetTokens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash NVARCHAR(128) NOT NULL UNIQUE,
    ExpiresAtUtc DATETIME2 NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UsedAtUtc DATETIME2 NULL,
    CONSTRAINT FK_PasswordResetTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Vehicles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    OwnerId UNIQUEIDENTIFIER NOT NULL,
    VehicleName NVARCHAR(100) NOT NULL,
    VehicleNumber NVARCHAR(30) NOT NULL UNIQUE,
    VehicleType INT NOT NULL,
    Color NVARCHAR(40) NOT NULL,
    Seats INT NOT NULL,
    RcImagePath NVARCHAR(500) NULL,
    VehicleImagePath NVARCHAR(500) NULL,
    IsVerified BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAtUtc DATETIME2 NULL,
    CONSTRAINT FK_Vehicles_Users FOREIGN KEY (OwnerId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE RideOffers (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    DriverId UNIQUEIDENTIFIER NOT NULL,
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    OriginName NVARCHAR(300) NOT NULL,
    OriginLatitude FLOAT NOT NULL,
    OriginLongitude FLOAT NOT NULL,
    DestinationName NVARCHAR(300) NOT NULL,
    DestinationLatitude FLOAT NOT NULL,
    DestinationLongitude FLOAT NOT NULL,
    DepartureTimeUtc DATETIME2 NOT NULL,
    AvailableSeats INT NOT NULL,
    PricePerSeat DECIMAL(10,2) NOT NULL,
    VehicleName NVARCHAR(100) NULL,
    VehicleNumber NVARCHAR(30) NULL,
    RoutePolyline NVARCHAR(8000) NULL,
    DistanceKm FLOAT NULL,
    EtaMinutes INT NULL,
    Status INT NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAtUtc DATETIME2 NULL,
    CONSTRAINT FK_RideOffers_Driver FOREIGN KEY (DriverId) REFERENCES Users(Id),
    CONSTRAINT FK_RideOffers_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id)
);

CREATE INDEX IX_RideOffers_Departure_Status ON RideOffers(DepartureTimeUtc, Status);

CREATE TABLE RideBookings (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    RideOfferId UNIQUEIDENTIFIER NOT NULL,
    PassengerId UNIQUEIDENTIFIER NOT NULL,
    SeatsBooked INT NOT NULL,
    PassengerPickupName NVARCHAR(300) NOT NULL,
    PassengerPickupAddress NVARCHAR(500) NOT NULL,
    PassengerPickupLatitude FLOAT NOT NULL,
    PassengerPickupLongitude FLOAT NOT NULL,
    PassengerDropName NVARCHAR(300) NOT NULL,
    PassengerDropAddress NVARCHAR(500) NOT NULL,
    PassengerDropLatitude FLOAT NOT NULL,
    PassengerDropLongitude FLOAT NOT NULL,
    Status INT NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CancelledAtUtc DATETIME2 NULL,
    CONSTRAINT FK_RideBookings_RideOffers FOREIGN KEY (RideOfferId) REFERENCES RideOffers(Id) ON DELETE CASCADE,
    CONSTRAINT FK_RideBookings_Passenger FOREIGN KEY (PassengerId) REFERENCES Users(Id)
);

CREATE INDEX IX_RideBookings_Ride_Passenger ON RideBookings(RideOfferId, PassengerId);

CREATE TABLE Payments (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BookingId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    TransactionId NVARCHAR(150) NOT NULL UNIQUE,
    PaymentStatus INT NOT NULL,
    PaymentMethod INT NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    VerifiedAtUtc DATETIME2 NULL,
    CONSTRAINT FK_Payments_Bookings FOREIGN KEY (BookingId) REFERENCES RideBookings(Id),
    CONSTRAINT FK_Payments_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(120) NOT NULL,
    Message NVARCHAR(1000) NOT NULL,
    IsRead BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ReadAtUtc DATETIME2 NULL,
    CONSTRAINT FK_Notifications_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE INDEX IX_Notifications_User_Read_Created ON Notifications(UserId, IsRead, CreatedAtUtc);

CREATE TABLE Reviews (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    RideOfferId UNIQUEIDENTIFIER NOT NULL,
    ReviewerId UNIQUEIDENTIFIER NOT NULL,
    RevieweeId UNIQUEIDENTIFIER NOT NULL,
    Rating INT NOT NULL,
    Comment NVARCHAR(1000) NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Reviews_RideOffers FOREIGN KEY (RideOfferId) REFERENCES RideOffers(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Reviews_Reviewer FOREIGN KEY (ReviewerId) REFERENCES Users(Id),
    CONSTRAINT FK_Reviews_Reviewee FOREIGN KEY (RevieweeId) REFERENCES Users(Id),
    CONSTRAINT UX_Reviews_Ride_Reviewer_Reviewee UNIQUE (RideOfferId, ReviewerId, RevieweeId),
    CONSTRAINT CK_Reviews_Rating CHECK (Rating BETWEEN 1 AND 5)
);

CREATE TABLE RideLocationUpdates (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    RideOfferId UNIQUEIDENTIFIER NOT NULL,
    DriverId UNIQUEIDENTIFIER NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    Heading FLOAT NULL,
    SpeedKph FLOAT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_RideLocationUpdates_RideOffers FOREIGN KEY (RideOfferId) REFERENCES RideOffers(Id) ON DELETE CASCADE,
    CONSTRAINT FK_RideLocationUpdates_Driver FOREIGN KEY (DriverId) REFERENCES Users(Id)
);

CREATE INDEX IX_RideLocationUpdates_Ride_Created ON RideLocationUpdates(RideOfferId, CreatedAtUtc);
